import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/utils/Toaste";
import { UserProvider } from "~/context/userContext";
import { ThemeProvider } from "./_components/theme-provider";
import { useTheme } from "next-themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body className={geist.className}>
        <TRPCReactProvider>
          <UserProvider>
          <ThemeProvider defaultTheme="dark">
            {children}
            <Toaster />
            </ThemeProvider>
          </UserProvider>
          </TRPCReactProvider>
      </body>
    </html>
  );
}
